---
# Global variables
{{- $postgresName := .Values.postgresName }}
{{- $serviceNameValue := .Values.serviceName }}
{{- $namespace :=  .Values.namespace }}

# Appointment Service
{{- range untilStep 0 (int .Values.replicaCount) 1}}
  {{- $index := . }}
  {{- $postgresServiceName := printf "%s-%d" $postgresName $index }}
  {{- with $.Values }}
    {{- $serviceDeploymentName := printf "%s%s-%d" $serviceNameValue "-deployment" $index }}
    {{- $serviceName := printf "%s-%d" $serviceNameValue $index }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceDeploymentName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $serviceDeploymentName }}
spec:
  selector:
    matchLabels:
      app: {{ $serviceDeploymentName }}
  template:
    metadata:
      labels:
        app: {{ $serviceDeploymentName }}
    spec:
      initContainers:
        - name: init-database
          image: busybox:1.36.1
          command:
            - sh
            - -c
            - >
              until nslookup {{ printf "%s.%s.svc.cluster.local" $postgresServiceName $namespace }}; do
                echo 'Waiting for postgres DB to initiate';
                sleep 2;
              done
      containers:
        - name: {{ $serviceName }}
          image: {{ .serviceImage }}
          env:
            - name: DATABASE_HOST
              value: {{ $postgresServiceName }}
            - name: KAFKA_BOOTSTRAP_HOST
              value: {{ .global.microservice.KAFKA_BOOTSTRAP_HOST }}
            - name: KAFKA_BOOTSTRAP_PORT
              value: {{ .global.microservice.KAFKA_BOOTSTRAP_PORT | quote }}
            - name: EUREKA_HOST
              value: {{ .global.microservice.EUREKA_HOST }}
            - name: SCHEMA_REGISTRY_HOST
              value: {{ .global.microservice.SCHEMA_REGISTRY_HOST }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $serviceDeploymentName }}
spec:
  selector:
    app: {{ $serviceDeploymentName }}
  ports:
    - protocol: TCP
      port: {{ .servicePort }}
  type: ClusterIP
---
# Appointment postgres
  {{- $postgresDeploymentName := printf "%s%s-%d" $postgresName "-deployment" $index }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $postgresDeploymentName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $postgresDeploymentName }}
spec:
  selector:
    matchLabels:
      app: {{ $postgresDeploymentName }}
  template:
    metadata:
      labels:
        app: {{ $postgresDeploymentName }}
    spec:
      containers:
        - name: {{ $postgresServiceName }}
          image: {{ $.Values.global.postgres.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .global.postgres.POSTGRES_USER }}
            - name: POSTGRES_PASSWORD
              value: {{ .global.postgres.POSTGRES_PASSWORD }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $postgresServiceName }}
  namespace: {{ $namespace }}
  labels:
    app: {{ $postgresDeploymentName }}
spec:
  selector:
    app: {{ $postgresDeploymentName }}
  ports:
    - protocol: TCP
      port: {{ .global.postgres.port }}
  type: ClusterIP
---
  {{- end }}
{{- end }}